### ISSUE TITLE
Furnace Right Click bug

### ISSUE THREAD

**Issue by Tim3game** [TheBusyBiscuit/CS-CoreLib#19]
## Description
When I have installed Slimefun with CS-CoreLib, there appears a bug with the furnace, that when I take the items from the furnace with a Right Click (Taking out half of the items), instead of taking out the half I wanted, it updates and takes ALL of the items in the current slot. I reported this 2 times on the Slimefun Issues page, but I found out but when I take out CS-CoreLib, that it's doesn't appears and maybe it's a CS-CoreLib bug.

## Server Log
No errors in console.

## Evidence / Proof
![sffurnacebug](https://cloud.githubusercontent.com/assets/10467214/24914940/1053d3ae-1ed6-11e7-9032-591b6b719e05.gif)

## Environment
**Minecraft version:** 1.11.2 (/sf versions: CraftBukkit v1_11_R1)
**Spigot version:** git-Spigot-d276ab1-d219213 (API: 1.11.2-R0.1-SNAPSHOT)
**CS-CoreLib version:** 1.5.14
**Slimefun version:** 4.1.6
**- HotbarPets:** 1.1
**- ExoticGarden:** 1.6.3

**Comment by TheBusyBiscuit** [comment]
That should not be caused by CS-CoreLib or Slimefun...
