### ISSUE TITLE
Heads

### ISSUE THREAD

**Issue by QueenKisaki** [TheBusyBiscuit/CS-CoreLib#23]
Is there anyway to turn off mob heads from dropping? None of my plugins do that so I'm assuming it cscorelib. It gets annoying the amount they drop so I just want to remove it.

**Comment by erik1988** [comment]
I doubt that its caused by this plugin. You should list your plugins here.

**Comment by QueenKisaki** [comment]
![plugins](https://user-images.githubusercontent.com/22261674/27255052-70592e5c-535b-11e7-87ca-66aad80b2998.png)

**Comment by QueenKisaki** [comment]
Thank you, I'm an idiot. It was craftbook.
