### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by claer** [TheBusyBiscuit/CS-CoreLib#24]
Hello,

I checked most of sites that host CS-CoreLib plugin and didn't find one in version 1.5.16, as tagged on GitHub. I even grepped the output of the update api request to curseforge. The output also shows 1.5.15.
In order to get around the "issue", I'd like to have some guidance in the wiki for building the library myself (same apply for Slimefun4). So that I can upgrade the server I manage to 1.12. 

Thanks for your nice plugin and all your work.

Claer

**Comment by TheBusyBiscuit** [comment]
1.5.15 has 1.12 Support. https://dev.bukkit.org/projects/cs-corelib/files/2433952
In fact, 1.5.15 is actually 1.5.16, it is just named wrongly.
