### ISSUE TITLE
Unable to build CSCoreLib : unable to download Towny

### ISSUE THREAD

**Issue by Poslovitch** [TheBusyBiscuit/CS-CoreLib#30]
After trying a few times to build Slimefun, it seems the error comes from CSCoreLib, which cannot be built because Maven can't download Towny.

The error probably comes from the fact that towny-repo no longer exists. I did some google-ing and found this : https://github.com/LlmDl/Towny/issues/2572. Which doesn't help us further but may be a good point to start from.

**Comment by TheBusyBiscuit** [comment]
I can confirm this.
I still dislike Maven.
And I cannot build anything either.

**Comment by TheBusyBiscuit** [comment]
@RoboMWM

**Comment by Poslovitch** [comment]
Closing : you fixed it here https://github.com/TheBusyBiscuit/CS-CoreLib/commit/47bb8d9ea8a569c7dc019e9f7be80c6b8bf0dcb3

**Comment by TheBusyBiscuit** [comment]
Not fixed at all.

I know nothing about Maven.

**Comment by Poslovitch** [comment]
This is exactly the pr I was about to make, which was successfully building CsCoreLib ^^

**Comment by TheBusyBiscuit** [comment]
It is failing for me.

"Failed to execute goal on project CSCoreLibPlugin: Could not resolve dependencies for project me.m
rCookieSlime:CSCoreLibPlugin:jar:1.5.16: Could not find artifact com.github.LlmDl:Towny:jar:7d02942180 in
paper-repo (https://repo.destroystokyo.com/repository/maven-public/)"

**Comment by TheBusyBiscuit** [comment]
Fixed in https://github.com/TheBusyBiscuit/CS-CoreLib/commit/49032c3ff0efb690a03aece2066527d36725ec95
