### ISSUE TITLE
Add support for RedProtect protection

### ISSUE THREAD

**Issue by DrOreo002** [TheBusyBiscuit/CS-CoreLib#39]
so as I said 5 days ago, there's a bug with RedProtect. Can you please fix it so the Android Miner can't break region with that has RedProtect?

**Comment by DrOreo002** [comment]
Hmmm, I think I can fix this.. Can you tell me what class that check for location or block that the Android Miner will break?.

Its kinda hard to find tbh

**Comment by TheBusyBiscuit** [comment]
@DrOreo002 Again... "fix" is not the appropriate term here.

And you just need to write a ProtectionHandler
https://github.com/TheBusyBiscuit/CS-CoreLib/tree/master/src/me/mrCookieSlime/CSCoreLibPlugin/protection/modules

And then register it here:
https://github.com/TheBusyBiscuit/CS-CoreLib/blob/master/src/me/mrCookieSlime/CSCoreLibPlugin/protection/ProtectionManager.java#L66

**Comment by DrOreo002** [comment]
xD, sorry about that. I'll try to make it asap. Ty for the help!

**Comment by DrOreo002** [comment]
Done. please approve it
https://github.com/TheBusyBiscuit/CS-CoreLib/pull/40
