### ISSUE TITLE
Crash Server

### ISSUE THREAD

**Issue by Sakanas** [TheBusyBiscuit/CS-CoreLib#57]
https://pastebin.com/MLB3SLKy
The paper team told me this.
Can you tell me how to solve it?

''me.mrCookieSlime.CSCoreLibPlugin is setting skull itemmeta synchronously and the server is having to lookup the profile, resulting in a blocking call out to Mojang.

Mojang is either taking too long to respond, or the plugin is making so many calls, that your server is spending all its time waiting for profile data rather than ticking.

If I remember correctly, the workaround for this is to get the player profiles asynchronously and then take those profiles and set them on the tile entity synchronously using the scheduler or your preferred task chain. You may need to forward that information to the developer''

**Comment by Sakanas** [comment]
Is there another way I can solve this? for example swapping paper by spigot

**Comment by Sakanas** [comment]
the server does not quite turn it off it just kicks all the players, is there any way of it just kicking 1 player, I've always used this plugin with spigot and it never happened that.

**Comment by TheBusyBiscuit** [comment]
Fixed in https://github.com/TheBusyBiscuit/Slimefun4/commit/11fec71a9471953a490118a971003f2cd85ef04a
