### ISSUE TITLE
WorldGuard Fix

### ISSUE THREAD

**Issue by xH3LLRAIZ3Rx** [TheBusyBiscuit/CS-CoreLib#58]
I am unable to fork CS-CoreLib to make a PR myself, so here is the code to fix the WorldGuard module:

`import com.sk89q.worldedit.bukkit.BukkitAdapter;
import com.sk89q.worldedit.util.Location;
import com.sk89q.worldedit.world.World;
import com.sk89q.worldguard.LocalPlayer;
import com.sk89q.worldguard.WorldGuard;
import com.sk89q.worldguard.bukkit.WorldGuardPlugin;
import com.sk89q.worldguard.protection.flags.Flags;
import com.sk89q.worldguard.protection.regions.RegionContainer;
import com.sk89q.worldguard.protection.regions.RegionQuery;
import me.mrCookieSlime.CSCoreLibPlugin.protection.ProtectionModule;
import org.bukkit.block.Block;
import org.bukkit.entity.Player;

public class WorldGuardProtectionModule implements ProtectionModule {

	WorldGuardPlugin wg = WorldGuardPlugin.inst();
	String worldname = "world";
	World wgWorld = WorldGuard.getInstance().getPlatform().getWorldByName(worldname);
	RegionContainer manager = WorldGuard.getInstance().getPlatform().getRegionContainer();
    RegionQuery query = manager.createQuery();

	public boolean canBuild(Player player, Block b) {
		Location loc = BukkitAdapter.adapt(b.getLocation());
        LocalPlayer lp = WorldGuardPlugin.inst().wrapPlayer(player);
		return query.testState(loc, lp, Flags.BUILD);
	}
	
	public boolean canAccessChest(Player player, Block b) {
		Location loc = BukkitAdapter.adapt(b.getLocation());
		LocalPlayer lp = WorldGuardPlugin.inst().wrapPlayer(player);
		return query.testBuild(loc, lp, Flags.INTERACT, Flags.CHEST_ACCESS);
	}

	@Override
	public String getName() {
		return "WorldGuard";
	}

}`

**Comment by TheBusyBiscuit** [comment]
And the required maven repo?

**Comment by xH3LLRAIZ3Rx** [comment]
`        <dependency>
            <groupId>com.sk89q.worldguard</groupId>
            <artifactId>worldguard-core</artifactId>
            <version>7.0.0-SNAPSHOT</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>com.sk89q.worldedit</groupId>
            <artifactId>worldedit-core</artifactId>
            <version>7.0.0-SNAPSHOT</version>
            <scope>provided</scope>
        </dependency>`

**Comment by xH3LLRAIZ3Rx** [comment]
its the same maven repo, just different artifactId

**Comment by xH3LLRAIZ3Rx** [comment]
Yikes, will update code in a minute, seems like BukkitAdapter is no longer public..

**Comment by xH3LLRAIZ3Rx** [comment]
`import com.sk89q.worldedit.bukkit.BukkitAdapter;
import com.sk89q.worldedit.util.Location;
import com.sk89q.worldedit.world.World;
import com.sk89q.worldguard.LocalPlayer;
import com.sk89q.worldguard.WorldGuard;
import com.sk89q.worldguard.bukkit.WorldGuardPlugin;
import com.sk89q.worldguard.protection.flags.DefaultFlag;
import com.sk89q.worldguard.protection.flags.Flags;
import com.sk89q.worldguard.protection.regions.RegionContainer;
import com.sk89q.worldguard.protection.regions.RegionQuery;
import me.mrCookieSlime.CSCoreLibPlugin.protection.ProtectionModule;
import org.bukkit.block.Block;
import org.bukkit.entity.Player;

import com.sk89q.worldguard.bukkit.WGBukkit;

public class WorldGuardProtectionModule implements ProtectionModule {

	WorldGuardPlugin wg = WGBukkit.getPlugin();
	String worldname = "world";
	World wgWorld = WorldGuard.getInstance().getPlatform().getWorldByName(worldname);
	RegionContainer manager = WorldGuard.getInstance().getPlatform().getRegionContainer();
    RegionQuery query = manager.createQuery();

	public boolean canBuild(Player player, Block b) {
		Location loc = BukkitAdapter.adapt(b.getLocation());
        LocalPlayer lp = WorldGuardPlugin.inst().wrapPlayer(player);
		return query.testState(loc, lp, Flags.BUILD);
	}
	
	public boolean canAccessChest(Player player, Block b) {
		Location loc = BukkitAdapter.adapt(b.getLocation());
		LocalPlayer lp = WorldGuardPlugin.inst().wrapPlayer(player);
		return query.testBuild(loc, lp, DefaultFlag.INTERACT, DefaultFlag.CHEST_ACCESS);
	}

	@Override
	public String getName() {
		return "WorldGuard";
	}

}`

**Comment by xH3LLRAIZ3Rx** [comment]
I reposted that just in case, updated the maven depends on my end to the one above

**Comment by xH3LLRAIZ3Rx** [comment]
Edited the code, was using old imports, WGBukkit is no longer a thing.
