### ISSUE TITLE
Can CS-CoreLib support AcidIsland?

### ISSUE THREAD

**Issue by Rothes** [TheBusyBiscuit/CS-CoreLib#67]
AcidIsland plugin is a kind of AskyBlock.
I wish it can supports that.

**Comment by sarhatabaot** [comment]
Perhaps it should support BentoBox instead. BentoBox includes bSkyblock & AcidIsland.

**Comment by TheBusyBiscuit** [comment]
@Poslovitch

**Comment by Rothes** [comment]
Just edit import and somewhere else on Askyblockprotection,I think

**Comment by Poslovitch** [comment]
@TheBusyBiscuit Shall I do that in this package? https://github.com/TheBusyBiscuit/CS-CoreLib/tree/master/src/me/mrCookieSlime/CSCoreLibPlugin/protection/modules

**Comment by Rothes** [comment]
> @TheBusyBiscuit我可以在这个套餐中这样做吗？https://github.com/TheBusyBiscuit/CS-CoreLib/tree/master/src/me/mrCookieSlime/CSCoreLibPlugin/protection/modules

And there?
https://github.com/TheBusyBiscuit/CS-CoreLib/blob/master/src/me/mrCookieSlime/CSCoreLibPlugin/protection/ProtectionManager.java

**Comment by TheBusyBiscuit** [comment]
Yup, both. @Poslovitch @Rothes

**Comment by Poslovitch** [comment]
Thanks. Could you please assign me to the issue @TheBusyBiscuit (if you can do so) ?

**Comment by TheBusyBiscuit** [comment]
@Poslovitch I cannot.
