### ISSUE TITLE
Player interaction in town throws error

### ISSUE THREAD

**Issue by ZackRuybal** [TheBusyBiscuit/CS-CoreLib#83]
## Description (Required)
On interaction with any of the machines (the Enhanced Crafting Table is what I used in the example), CS-Core throws an error that involves towny to see if a player has the ability to look inside of a chest.

## Steps to reproduce the Issue (Required)
https://www.youtube.com/watch?v=HkKuMrTj8nQ

## Expected behavior (Required)
The GUI to open for the Enhanced Crafting Table

## Server Log / Error Report
https://pastebin.com/xRYmSLjB

## Environment (Required)
This server is running Paper version git-Paper-39 (MC: 1.14.1) (Implementing API version 1.14.1-R0.1-SNAPSHOT) 

 - Minecraft Version: 1.14.1
 - CS-CoreLib Version: Dev 46 (git adec944a)
 - Towny Version: 0.93.1.0

**Comment by TheBusyBiscuit** [comment]
Update CS-CoreLib, there has been a newer version with a fix already.
